rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  comma-dangle:
    - 2
    - always-multiline
plugins:
  - react
  - react-native
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true,
    experimentalObjectRestSpread: true
extends:
  - eslint:recommended
  - plugin:react/recommended